# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7s50csga324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/joann/Desktop/FINAL_FINAL_FPGA/FINAL_FINAL_FPGA.cache/wt [current_project]
set_property parent.project_path C:/Users/joann/Desktop/FINAL_FINAL_FPGA/FINAL_FINAL_FPGA.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/joann/Desktop/FINAL_FINAL_FPGA/FINAL_FINAL_FPGA.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {{C:/Users/joann/OneDrive - IIIT Hyderabad/2-1/VLSI Design/Project/verilog/cla5.v}}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/joann/Downloads/boolean_cla.xdc
set_property used_in_implementation false [get_files C:/Users/joann/Downloads/boolean_cla.xdc]


synth_design -top cla5_registered -part xc7s50csga324-1


write_checkpoint -force -noxdef cla5_registered.dcp

catch { report_utilization -file cla5_registered_utilization_synth.rpt -pb cla5_registered_utilization_synth.pb }
